version: "3.7"
services:
  tpfoyer17:
    image: abdelmouhaimen/tpfoyer17:66
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbmysql:3306/tpFoyer17?createDatabaseIfNotExist=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - dbmysql
    networks:
      - app-network

  dbmysql:
    image: "mysql:5.6"
    container_name: dbmysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

  angular-app:
    image: abdelmouhaimen/projetfoyerfrontmain:v1
    ports:
      - "4200:80"
    restart: always
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
